[package]
name = "shunting-yard"
version = "0.1.0"
edition = "2021"
authors = ["Onuwa Nnachi Isaac <isaac.onuwa@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
